site_name: YYC's Workbench

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - meta
  - attr_list
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.details
  - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - roamlinks 
  - tags

nav:
  - index.md
  - Map of Content:
    - Quick References: "MOC/202207311054_moc_quick_ref.md"
    - Digital Signal Processing: "MOC/202207182111_moc_dsp.md"
    - Audio Engineering: "MOC/202207182345_moc_audio_eng.md"
    - Troubleshooting: "MOC/202207222056_moc_troubleshooting.md"
    - Math: "MOC/202305210816_moc_math.md"
    - Programming Languages: "MOC/202305210835_moc_programming_language.md"
    - Uncategorized: "MOC/202305210846_moc_uncategorized.md"

